export const year = [
		{
			id:1,
			month: 'Januar',
			days: [
				{date: '1', city: "Taraz", empty: true},
				{date: '2', city: "Almaty", empty: false},
				{date: '3', city: "Semey", empty: true},
				{date: '4', city: "Aktau", empty: false},
				{date: '5', city: "Semey", empty: false},
				{date: '6', city: "Almaty", empty: true},
				{date: '7', city: "Astana", empty: true},
				{date: '8', city: "Aktau", empty: true},
				{date: '9', city: "Atyrau", empty: false},
				{date: '10', city: "Almaty", empty: true},
				{date: '11', city: "Astana", empty: true},
				{date: '12', city: "Aktau", empty: false},
				{date: '13', city: "Taraz", empty: false},
				{date: '14', city: "Almaty", empty: true},
				{date: '15', city: "Astana", empty: true},
				{date: '16', city: "Aktau", empty: true},
				{date: '17', city: "Aktobe", empty: true},
				{date: '18', city: "Almaty", empty: true},
				{date: '19', city: "Shimkent", empty: false},
				{date: '20', city: "Aktau", empty: false},
				{date: '21', city: "Taraz", empty: true},
				{date: '22', city: "Almaty", empty: false},
				{date: '23', city: "", empty: false},
				{date: '24', city: "Aktau", empty: true},
				{date: '25', city: "Taraz", empty: true},
				{date: '26', city: "Almaty", empty: false},
				{date: '27', city: "Astana", empty: true},
				{date: '28', city: "Aktau", empty: true},
				{date: '29', city: "Taraz", empty: true},
			]
		},
		{
		id:2,
		month: 'February',
		days: [
			{date: '1', city: "Taraz", empty: true},
			{date: '2', city: "Almaty", empty: false},
			{date: '3', city: "Semey", empty: true},
			{date: '4', city: "Aktau", empty: false},
			{date: '5', city: "Semey", empty: true},
			{date: '6', city: "Almaty", empty: false},
			{date: '7', city: "Astana", empty: false},
			{date: '8', city: "Aktau", empty: false},
			{date: '9', city: "Atyrau", empty: true},
			{date: '10', city: "Almaty", empty: false},
			{date: '11', city: "Astana", empty: false},
			{date: '12', city: "Aktau", empty: false},
			{date: '13', city: "Taraz", empty: false},
			{date: '14', city: "Almaty", empty: false},
			{date: '15', city: "Astana", empty: false},
			{date: '16', city: "Aktau", empty: true},
			{date: '17', city: "Aktobe", empty: false},
			{date: '18', city: "Almaty", empty: true},
			{date: '19', city: "Shimkent", empty: true},
			{date: '20', city: "Aktau", empty: false},
			{date: '21', city: "Taraz", empty: true},
			{date: '22', city: "Almaty", empty: false},
			{date: '23', city: "", empty: true},
			{date: '24', city: "Aktau", empty: false},
			{date: '25', city: "Taraz", empty: false},
			{date: '26', city: "Almaty", empty: true},
			{date: '27', city: "Astana", empty: false},
			{date: '28', city: "Aktau", empty: false},
			{date: '29', city: "Taraz", empty: false},
		]
	},
	{
		id:3,
		month: 'March',
		days: [
				{date: '1', city: "Taraz", empty: true},
				{date: '2', city: "Almaty", empty: false},
				{date: '3', city: "Semey", empty: true},
				{date: '4', city: "Aktau", empty: false},
				{date: '5', city: "Semey", empty: false},
				{date: '6', city: "Almaty", empty: true},
				{date: '7', city: "Astana", empty: true},
				{date: '8', city: "Aktau", empty: true},
				{date: '9', city: "Atyrau", empty: false},
				{date: '10', city: "Almaty", empty: true},
				{date: '11', city: "Astana", empty: false},
				{date: '12', city: "Aktau", empty: false},
				{date: '13', city: "Taraz", empty: false},
				{date: '14', city: "Almaty", empty: true},
				{date: '15', city: "Astana", empty: true},
				{date: '16', city: "Aktau", empty: true},
				{date: '17', city: "Aktobe", empty: true},
				{date: '18', city: "Almaty", empty: true},
				{date: '19', city: "Shimkent", empty: false},
				{date: '20', city: "Aktau", empty: false},
				{date: '21', city: "Taraz", empty: true},
				{date: '22', city: "Almaty", empty: false},
				{date: '23', city: "", empty: false},
				{date: '24', city: "Aktau", empty: true},
				{date: '25', city: "Taraz", empty: true},
				{date: '26', city: "Almaty", empty: false},
				{date: '27', city: "Astana", empty: true},
				{date: '28', city: "Aktau", empty: true},
				{date: '29', city: "Taraz", empty: true},
			]
	},
	{
		id:4,
		month: 'April',
		days: [
			{date: '1', city: "Taraz", empty: true},
			{date: '2', city: "Almaty", empty: false},
			{date: '3', city: "Semey", empty: true},
			{date: '4', city: "Aktau", empty: false},
			{date: '5', city: "Semey", empty: true},
			{date: '6', city: "Almaty", empty: false},
			{date: '7', city: "Astana", empty: false},
			{date: '8', city: "Aktau", empty: false},
			{date: '9', city: "Atyrau", empty: true},
			{date: '10', city: "Almaty", empty: false},
			{date: '11', city: "Astana", empty: false},
			{date: '12', city: "Aktau", empty: false},
			{date: '13', city: "Taraz", empty: false},
			{date: '14', city: "Almaty", empty: false},
			{date: '15', city: "Astana", empty: false},
			{date: '16', city: "Aktau", empty: true},
			{date: '17', city: "Aktobe", empty: false},
			{date: '18', city: "Almaty", empty: true},
			{date: '19', city: "Shimkent", empty: true},
			{date: '20', city: "Aktau", empty: false},
			{date: '21', city: "Taraz", empty: true},
			{date: '22', city: "Almaty", empty: false},
			{date: '23', city: "", empty: true},
			{date: '24', city: "Aktau", empty: false},
			{date: '25', city: "Taraz", empty: false},
			{date: '26', city: "Almaty", empty: true},
			{date: '27', city: "Astana", empty: false},
			{date: '28', city: "Aktau", empty: false},
			{date: '29', city: "Taraz", empty: false},
		]
	},
	{
		id:5,
		month: 'May',
		days: [
			{date: '1', city: "Taraz", empty: true},
			{date: '2', city: "Almaty", empty: false},
			{date: '3', city: "Semey", empty: true},
			{date: '4', city: "Aktau", empty: false},
			{date: '5', city: "Semey", empty: true},
			{date: '6', city: "Almaty", empty: false},
			{date: '7', city: "Astana", empty: true},
			{date: '8', city: "Aktau", empty: false},
			{date: '9', city: "Atyrau", empty: true},
			{date: '10', city: "Almaty", empty: false},
			{date: '11', city: "Astana", empty: true},
			{date: '12', city: "Aktau", empty: false},
			{date: '13', city: "Taraz", empty: false},
			{date: '14', city: "Almaty", empty: true},
			{date: '15', city: "Astana", empty: false},
			{date: '16', city: "Aktau", empty: true},
			{date: '17', city: "Aktobe", empty: false},
			{date: '18', city: "Almaty", empty: true},
			{date: '19', city: "Shimkent", empty: true},
			{date: '20', city: "Aktau", empty: false},
			{date: '21', city: "Taraz", empty: true},
			{date: '22', city: "Almaty", empty: false},
			{date: '23', city: "", empty: true},
			{date: '24', city: "Aktau", empty: false},
			{date: '25', city: "Taraz", empty: true},
			{date: '26', city: "Almaty", empty: true},
			{date: '27', city: "Astana", empty: false},
			{date: '28', city: "Aktau", empty: false},
			{date: '29', city: "Taraz", empty: true},
		]
	},
	{
		id:6,
		month: 'June',
		days: [
				{date: '1', city: "Taraz", empty: true},
				{date: '2', city: "Almaty", empty: false},
				{date: '3', city: "Semey", empty: true},
				{date: '4', city: "Aktau", empty: false},
				{date: '5', city: "Semey", empty: false},
				{date: '6', city: "Almaty", empty: true},
				{date: '7', city: "Astana", empty: true},
				{date: '8', city: "Aktau", empty: true},
				{date: '9', city: "Atyrau", empty: false},
				{date: '10', city: "Almaty", empty: true},
				{date: '11', city: "Astana", empty: false},
				{date: '12', city: "Aktau", empty: false},
				{date: '13', city: "Taraz", empty: false},
				{date: '14', city: "Almaty", empty: true},
				{date: '15', city: "Astana", empty: true},
				{date: '16', city: "Aktau", empty: true},
				{date: '17', city: "Aktobe", empty: true},
				{date: '18', city: "Almaty", empty: true},
				{date: '19', city: "Shimkent", empty: false},
				{date: '20', city: "Aktau", empty: false},
				{date: '21', city: "Taraz", empty: true},
				{date: '22', city: "Almaty", empty: false},
				{date: '23', city: "", empty: false},
				{date: '24', city: "Aktau", empty: true},
				{date: '25', city: "Taraz", empty: true},
				{date: '26', city: "Almaty", empty: false},
				{date: '27', city: "Astana", empty: true},
				{date: '28', city: "Aktau", empty: true},
				{date: '29', city: "Taraz", empty: true},
			]
	},
	{
		id:7,
		month: 'July',
		days: [
			{date: '1', city: "Taraz", empty: true},
			{date: '2', city: "Almaty", empty: false},
			{date: '3', city: "Semey", empty: true},
			{date: '4', city: "Aktau", empty: false},
			{date: '5', city: "Semey", empty: true},
			{date: '6', city: "Almaty", empty: false},
			{date: '7', city: "Astana", empty: false},
			{date: '8', city: "Aktau", empty: false},
			{date: '9', city: "Atyrau", empty: true},
			{date: '10', city: "Almaty", empty: false},
			{date: '11', city: "Astana", empty: false},
			{date: '12', city: "Aktau", empty: false},
			{date: '13', city: "Taraz", empty: false},
			{date: '14', city: "Almaty", empty: false},
			{date: '15', city: "Astana", empty: false},
			{date: '16', city: "Aktau", empty: true},
			{date: '17', city: "Aktobe", empty: false},
			{date: '18', city: "Almaty", empty: true},
			{date: '19', city: "Shimkent", empty: true},
			{date: '20', city: "Aktau", empty: false},
			{date: '21', city: "Taraz", empty: true},
			{date: '22', city: "Almaty", empty: false},
			{date: '23', city: "", empty: true},
			{date: '24', city: "Aktau", empty: false},
			{date: '25', city: "Taraz", empty: false},
			{date: '26', city: "Almaty", empty: true},
			{date: '27', city: "Astana", empty: false},
			{date: '28', city: "Aktau", empty: false},
			{date: '29', city: "Taraz", empty: false},
		]
	},
	{
		id:8,
		month: 'August',
		days: [
				{date: '1', city: "Taraz", empty: true},
				{date: '2', city: "Almaty", empty: false},
				{date: '3', city: "Semey", empty: true},
				{date: '4', city: "Aktau", empty: false},
				{date: '5', city: "Semey", empty: false},
				{date: '6', city: "Almaty", empty: true},
				{date: '7', city: "Astana", empty: true},
				{date: '8', city: "Aktau", empty: true},
				{date: '9', city: "Atyrau", empty: false},
				{date: '10', city: "Almaty", empty: true},
				{date: '11', city: "Astana", empty: false},
				{date: '12', city: "Aktau", empty: false},
				{date: '13', city: "Taraz", empty: false},
				{date: '14', city: "Almaty", empty: true},
				{date: '15', city: "Astana", empty: true},
				{date: '16', city: "Aktau", empty: true},
				{date: '17', city: "Aktobe", empty: true},
				{date: '18', city: "Almaty", empty: true},
				{date: '19', city: "Shimkent", empty: false},
				{date: '20', city: "Aktau", empty: false},
				{date: '21', city: "Taraz", empty: true},
				{date: '22', city: "Almaty", empty: false},
				{date: '23', city: "", empty: false},
				{date: '24', city: "Aktau", empty: true},
				{date: '25', city: "Taraz", empty: true},
				{date: '26', city: "Almaty", empty: false},
				{date: '27', city: "Astana", empty: true},
				{date: '28', city: "Aktau", empty: true},
				{date: '29', city: "Taraz", empty: true},
			]
	},
	{
		id:9,
		month: 'September',
		days: [
			{date: '1', city: "Taraz", empty: true},
			{date: '2', city: "Almaty", empty: false},
			{date: '3', city: "Semey", empty: true},
			{date: '4', city: "Aktau", empty: false},
			{date: '5', city: "Semey", empty: true},
			{date: '6', city: "Almaty", empty: false},
			{date: '7', city: "Astana", empty: false},
			{date: '8', city: "Aktau", empty: false},
			{date: '9', city: "Atyrau", empty: true},
			{date: '10', city: "Almaty", empty: false},
			{date: '11', city: "Astana", empty: false},
			{date: '12', city: "Aktau", empty: false},
			{date: '13', city: "Taraz", empty: false},
			{date: '14', city: "Almaty", empty: false},
			{date: '15', city: "Astana", empty: false},
			{date: '16', city: "Aktau", empty: true},
			{date: '17', city: "Aktobe", empty: false},
			{date: '18', city: "Almaty", empty: true},
			{date: '19', city: "Shimkent", empty: true},
			{date: '20', city: "Aktau", empty: false},
			{date: '21', city: "Taraz", empty: true},
			{date: '22', city: "Almaty", empty: false},
			{date: '23', city: "", empty: true},
			{date: '24', city: "Aktau", empty: false},
			{date: '25', city: "Taraz", empty: false},
			{date: '26', city: "Almaty", empty: true},
			{date: '27', city: "Astana", empty: false},
			{date: '28', city: "Aktau", empty: false},
			{date: '29', city: "Taraz", empty: false},
		]
	},
	{
		id:10,
		month: 'October',
		days: [
				{date: '1', city: "Taraz", empty: true},
				{date: '2', city: "Almaty", empty: false},
				{date: '3', city: "Semey", empty: true},
				{date: '4', city: "Aktau", empty: false},
				{date: '5', city: "Semey", empty: false},
				{date: '6', city: "Almaty", empty: true},
				{date: '7', city: "Astana", empty: true},
				{date: '8', city: "Aktau", empty: true},
				{date: '9', city: "Atyrau", empty: false},
				{date: '10', city: "Almaty", empty: true},
				{date: '11', city: "Astana", empty: false},
				{date: '12', city: "Aktau", empty: false},
				{date: '13', city: "Taraz", empty: false},
				{date: '14', city: "Almaty", empty: true},
				{date: '15', city: "Astana", empty: true},
				{date: '16', city: "Aktau", empty: true},
				{date: '17', city: "Aktobe", empty: true},
				{date: '18', city: "Almaty", empty: true},
				{date: '19', city: "Shimkent", empty: false},
				{date: '20', city: "Aktau", empty: false},
				{date: '21', city: "Taraz", empty: true},
				{date: '22', city: "Almaty", empty: false},
				{date: '23', city: "", empty: false},
				{date: '24', city: "Aktau", empty: true},
				{date: '25', city: "Taraz", empty: true},
				{date: '26', city: "Almaty", empty: false},
				{date: '27', city: "Astana", empty: true},
				{date: '28', city: "Aktau", empty: true},
				{date: '29', city: "Taraz", empty: true},
			]
	},
	{
		id:11,
		month: 'November',
		days: [
			{date: '1', city: "Taraz", empty: true},
			{date: '2', city: "Almaty", empty: false},
			{date: '3', city: "Semey", empty: false},
			{date: '4', city: "Aktau", empty: false},
			{date: '5', city: "Semey", empty: true},
			{date: '6', city: "Almaty", empty: false},
			{date: '7', city: "Astana", empty: false},
			{date: '8', city: "Aktau", empty: false},
			{date: '9', city: "Atyrau", empty: true},
			{date: '10', city: "Almaty", empty: true},
			{date: '11', city: "Astana", empty: false},
			{date: '12', city: "Aktau", empty: true},
			{date: '13', city: "Taraz", empty: false},
			{date: '14', city: "Almaty", empty: true},
			{date: '15', city: "Astana", empty: false},
			{date: '16', city: "Aktau", empty: true},
			{date: '17', city: "Aktobe", empty: true},
			{date: '18', city: "Almaty", empty: true},
			{date: '19', city: "Shimkent", empty: true},
			{date: '20', city: "Aktau", empty: true},
			{date: '21', city: "Taraz", empty: true},
			{date: '22', city: "Almaty", empty: false},
			{date: '23', city: "", empty: true},
			{date: '24', city: "Aktau", empty: false},
			{date: '25', city: "Taraz", empty: false},
			{date: '26', city: "Almaty", empty: true},
			{date: '27', city: "Astana", empty: false},
			{date: '28', city: "Aktau", empty: true},
			{date: '29', city: "Taraz", empty: false},
		]
	},
	{
		id:12,
		month: 'December',
		days: [
			{date: '1', city: "Taraz", empty: true},
			{date: '2', city: "Almaty", empty: false},
			{date: '3', city: "Semey", empty: true},
			{date: '4', city: "Aktau", empty: false},
			{date: '5', city: "Semey", empty: true},
			{date: '6', city: "Almaty", empty: false},
			{date: '7', city: "Astana", empty: false},
			{date: '8', city: "Aktau", empty: false},
			{date: '9', city: "Atyrau", empty: true},
			{date: '10', city: "Almaty", empty: false},
			{date: '11', city: "Astana", empty: false},
			{date: '12', city: "Aktau", empty: false},
			{date: '13', city: "Taraz", empty: false},
			{date: '14', city: "Almaty", empty: false},
			{date: '15', city: "Astana", empty: false},
			{date: '16', city: "Aktau", empty: true},
			{date: '17', city: "Aktobe", empty: false},
			{date: '18', city: "Almaty", empty: true},
			{date: '19', city: "Shimkent", empty: true},
			{date: '20', city: "Aktau", empty: false},
			{date: '21', city: "Taraz", empty: true},
			{date: '22', city: "Almaty", empty: false},
			{date: '23', city: "", empty: true},
			{date: '24', city: "Aktau", empty: false},
			{date: '25', city: "Taraz", empty: false},
			{date: '26', city: "Almaty", empty: true},
			{date: '27', city: "Astana", empty: false},
			{date: '28', city: "Aktau", empty: false},
			{date: '29', city: "Taraz", empty: false},
		]
	}

]